#!/bin/bash
set -ex

if [[ ! -d ${HOME}/.dotfiles ]] ; then
  git clone https://github.com/taylorsilva/dotfiles.git "${HOME}/.dotfiles"
  pushd "${HOME}/.dotfiles"
    # git submodule update --init
    rm "${HOME}/.bashrc" "${HOME}/.profile"
    stow bash neovim git
  popd
  git clone --depth=1 https://github.com/Bash-it/bash-it.git "${HOME}/.bash_it"
  ~/.bash_it/install.sh --no-modify-config

  mkdir -p "${HOME}/go"
fi

if [[ ! -d ${HOME}/tmuxfiles ]]; then
  git clone https://github.com/luan/tmuxfiles.git "${HOME}/tmuxfiles"
  pushd "${HOME}/tmuxfiles"
    ./install
  popd
fi
