#!/bin/bash
set -ex

# curl vimfiles.luan.sh/install | bash
if [[ ! -d ${HOME}/vimfiles ]] ; then
  git clone https://github.com/luan/vimfiles.git "${HOME}/vimfiles"
  pushd "${HOME}/vimfiles"
    ./bin/install --non-interactive
  popd
fi

if [[ ! -d ${HOME}/tmuxfiles ]]; then
  git clone https://github.com/luan/tmuxfiles.git "${HOME}/tmuxfiles"
  pushd "${HOME}/tmuxfiles"
    ./install
  popd
fi

if grep -e GOPATH "${HOME}/.profile"; then

  echo ".profile is already appended with user configuration"

else
  echo "Appending user configuration to .profile"

  cat <<-EOF >> "${HOME}/.profile"

# set user aliases

alias vi=nvim
EOF

fi

if grep -e GOPATH "${HOME}/.bashrc"; then

  echo ".bashrc is already appended with user configuration"

else
  echo "Appending user configuration to .bashrc"

  cat <<-EOF >> "${HOME}/.bashrc"

# set GOPATH

export GOPATH=${HOME}/workspace/go

# set default editor

export EDITOR=$(which nvim)

HISTSIZE=
HISTFILESIZE=
EOF

  mkdir -p "${HOME}/workspace/go"

fi
