#!/bin/bash
set -ex

if [[ ! -d ${HOME}/.dotfiles ]] ; then
  git clone https://github.com/taylorsilva/dotfiles.git "${HOME}/.dotfiles"
  pushd "${HOME}/.dotfiles"
    # git submodule update --init
    rm "${HOME}/.bashrc" "${HOME}/.profile"
    stow bash neovim git
  popd
  git clone --depth=1 https://github.com/Bash-it/bash-it.git "${HOME}/.bash_it"
  ~/.bash_it/install.sh --no-modify-config

  mkdir -p "${HOME}/go"

  #Finish neovim setup
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  nvim +PlugInstall +qa
fi

if [[ ! -d ${HOME}/tmuxfiles ]]; then
  git clone https://github.com/luan/tmuxfiles.git "${HOME}/tmuxfiles"
  pushd "${HOME}/tmuxfiles"
    ./install
  popd
fi
